/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.5.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import lombok.Data;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import yapily.sdk.models.AccountBalanceType;
import yapily.sdk.models.Amount;
import yapily.sdk.models.CreditLine;

/**
* AccountBalance
*/
    @JsonPropertyOrder({
        AccountBalance.JSON_PROPERTY_TYPE,
        AccountBalance.JSON_PROPERTY_DATE_TIME,
        AccountBalance.JSON_PROPERTY_BALANCE_AMOUNT,
        AccountBalance.JSON_PROPERTY_CREDIT_LINE_INCLUDED,
        AccountBalance.JSON_PROPERTY_CREDIT_LINES
    })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-17T11:34:20.056Z[Etc/UTC]")
@lombok.Builder(toBuilder=true) 
@lombok.Data
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class AccountBalance {
    public static final String JSON_PROPERTY_TYPE = "type";
    @JsonProperty("type")
    private AccountBalanceType type;

    public static final String JSON_PROPERTY_DATE_TIME = "dateTime";
    @JsonProperty("dateTime")
    private OffsetDateTime dateTime;

    public static final String JSON_PROPERTY_BALANCE_AMOUNT = "balanceAmount";
    @JsonProperty("balanceAmount")
    private Amount balanceAmount;

    public static final String JSON_PROPERTY_CREDIT_LINE_INCLUDED = "creditLineIncluded";
    @JsonProperty("creditLineIncluded")
    private Boolean creditLineIncluded;

    public static final String JSON_PROPERTY_CREDIT_LINES = "creditLines";
    @JsonProperty("creditLines")
    @lombok.Singular("creditLines") private List<CreditLine> creditLines;

}
