/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import lombok.Data;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import yapily.sdk.models.AccountBalance;
import yapily.sdk.models.AccountIdentification;
import yapily.sdk.models.AccountName;
import yapily.sdk.models.AccountType;
import yapily.sdk.models.ConsolidatedAccountInformation;
import yapily.sdk.models.UsageType;

/**
* Account
*/
    @JsonPropertyOrder({
        Account.JSON_PROPERTY_ID,
        Account.JSON_PROPERTY_TYPE,
        Account.JSON_PROPERTY_DESCRIPTION,
        Account.JSON_PROPERTY_BALANCE,
        Account.JSON_PROPERTY_CURRENCY,
        Account.JSON_PROPERTY_USAGE_TYPE,
        Account.JSON_PROPERTY_ACCOUNT_TYPE,
        Account.JSON_PROPERTY_NICKNAME,
        Account.JSON_PROPERTY_DETAILS,
        Account.JSON_PROPERTY_ACCOUNT_NAMES,
        Account.JSON_PROPERTY_ACCOUNT_IDENTIFICATIONS,
        Account.JSON_PROPERTY_ACCOUNT_BALANCES,
        Account.JSON_PROPERTY_CONSOLIDATED_ACCOUNT_INFORMATION
    })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-06T10:23:44.837Z[Etc/UTC]")
@lombok.Builder(toBuilder=true) 
@lombok.Data
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class Account {
    public static final String JSON_PROPERTY_ID = "id";
    @JsonProperty("id")
    private String id;

    public static final String JSON_PROPERTY_TYPE = "type";
    @JsonProperty("type")
    private String type;

    public static final String JSON_PROPERTY_DESCRIPTION = "description";
    @JsonProperty("description")
    private String description;

    public static final String JSON_PROPERTY_BALANCE = "balance";
    @JsonProperty("balance")
    private BigDecimal balance;

    public static final String JSON_PROPERTY_CURRENCY = "currency";
    @JsonProperty("currency")
    private String currency;

    public static final String JSON_PROPERTY_USAGE_TYPE = "usageType";
    @JsonProperty("usageType")
    private UsageType usageType;

    public static final String JSON_PROPERTY_ACCOUNT_TYPE = "accountType";
    @JsonProperty("accountType")
    private AccountType accountType;

    public static final String JSON_PROPERTY_NICKNAME = "nickname";
    @JsonProperty("nickname")
    private String nickname;

    public static final String JSON_PROPERTY_DETAILS = "details";
    @JsonProperty("details")
    private String details;

    public static final String JSON_PROPERTY_ACCOUNT_NAMES = "accountNames";
    @JsonProperty("accountNames")
    @lombok.Singular("accountNames") private List<AccountName> accountNames;

    public static final String JSON_PROPERTY_ACCOUNT_IDENTIFICATIONS = "accountIdentifications";
    @JsonProperty("accountIdentifications")
    @lombok.Singular("accountIdentifications") private Set<AccountIdentification> accountIdentifications;

    public static final String JSON_PROPERTY_ACCOUNT_BALANCES = "accountBalances";
    @JsonProperty("accountBalances")
    @lombok.Singular("accountBalances") private List<AccountBalance> accountBalances;

    public static final String JSON_PROPERTY_CONSOLIDATED_ACCOUNT_INFORMATION = "consolidatedAccountInformation";
    @JsonProperty("consolidatedAccountInformation")
    private ConsolidatedAccountInformation consolidatedAccountInformation;

}
