/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.6.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import lombok.Data;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * __Optional__. The type of address
 */
public enum AddressTypeEnum {
  
  BUSINESS("BUSINESS"),
  
  CORRESPONDENCE("CORRESPONDENCE"),
  
  DELIVERY_TO("DELIVERY_TO"),
  
  MAIL_TO("MAIL_TO"),
  
  PO_BOX("PO_BOX"),
  
  POSTAL("POSTAL"),
  
  RESIDENTIAL("RESIDENTIAL"),
  
  STATEMENT("STATEMENT"),
  
  UNKNOWN("UNKNOWN");

  private String value;

  AddressTypeEnum(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static AddressTypeEnum fromValue(String value) {
    for (AddressTypeEnum b : AddressTypeEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

