/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import lombok.Data;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import yapily.sdk.models.Categorisation;
import yapily.sdk.models.EnrichmentMerchant;
import yapily.sdk.models.TransactionHash;

/**
* Enrichment
*/
    @JsonPropertyOrder({
        Enrichment.JSON_PROPERTY_CATEGORISATION,
        Enrichment.JSON_PROPERTY_TRANSACTION_HASH,
        Enrichment.JSON_PROPERTY_CLEANSED_DESCRIPTION,
        Enrichment.JSON_PROPERTY_MERCHANT,
        Enrichment.JSON_PROPERTY_LOCATION,
        Enrichment.JSON_PROPERTY_PAYMENT_PROCESSOR,
        Enrichment.JSON_PROPERTY_CORRECTED_DATE
    })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-15T13:40:46.583Z[Etc/UTC]")
@lombok.Builder(toBuilder=true) 
@lombok.Data
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class Enrichment {
    public static final String JSON_PROPERTY_CATEGORISATION = "categorisation";
    @JsonProperty("categorisation")
    private Categorisation categorisation;

    public static final String JSON_PROPERTY_TRANSACTION_HASH = "transactionHash";
    @JsonProperty("transactionHash")
    private TransactionHash transactionHash;

    public static final String JSON_PROPERTY_CLEANSED_DESCRIPTION = "cleansedDescription";
    @JsonProperty("cleansedDescription")
    private String cleansedDescription;

    public static final String JSON_PROPERTY_MERCHANT = "merchant";
    @JsonProperty("merchant")
    private EnrichmentMerchant merchant;

    public static final String JSON_PROPERTY_LOCATION = "location";
    @JsonProperty("location")
    private String location;

    public static final String JSON_PROPERTY_PAYMENT_PROCESSOR = "paymentProcessor";
    @JsonProperty("paymentProcessor")
    private String paymentProcessor;

    public static final String JSON_PROPERTY_CORRECTED_DATE = "correctedDate";
    @JsonProperty("correctedDate")
    private OffsetDateTime correctedDate;

}
