/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.13.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import lombok.Data;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import yapily.sdk.models.EnrichedHistoricBalance;
import yapily.sdk.models.EnrichedPredictedBalance;

/**
* Enriched Balance information generated which include historic aggregated balances and predicted balances
*/
@ApiModel(description = "Enriched Balance information generated which include historic aggregated balances and predicted balances")
    @JsonPropertyOrder({
        EnrichedBalances.JSON_PROPERTY_ACCOUNT_IDS,
        EnrichedBalances.JSON_PROPERTY_INSTITUTIONS,
        EnrichedBalances.JSON_PROPERTY_HISTORIC,
        EnrichedBalances.JSON_PROPERTY_PREDICTED
    })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-07T11:29:02.836Z[Etc/UTC]")
@lombok.Builder(toBuilder=true) 
@lombok.Data
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class EnrichedBalances {
    public static final String JSON_PROPERTY_ACCOUNT_IDS = "accountIds";
    @JsonProperty("accountIds")
    @lombok.Singular("accountIds") private List<String> accountIds;

    public static final String JSON_PROPERTY_INSTITUTIONS = "institutions";
    @JsonProperty("institutions")
    @lombok.Singular("institutions") private List<String> institutions;

    public static final String JSON_PROPERTY_HISTORIC = "historic";
    @JsonProperty("historic")
    @lombok.Singular("historic") private List<EnrichedHistoricBalance> historic;

    public static final String JSON_PROPERTY_PREDICTED = "predicted";
    @JsonProperty("predicted")
    @lombok.Singular("predicted") private List<EnrichedPredictedBalance> predicted;

}
