/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.6.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import lombok.Data;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
* Links
*/
    @JsonPropertyOrder({
        Links.JSON_PROPERTY_SELF,
        Links.JSON_PROPERTY_FIRST,
        Links.JSON_PROPERTY_LAST,
        Links.JSON_PROPERTY_NEXT,
        Links.JSON_PROPERTY_PREVIOUS
    })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-17T11:55:38.294Z[Etc/UTC]")
@lombok.Builder(toBuilder=true) 
@lombok.Data
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class Links {
    public static final String JSON_PROPERTY_SELF = "self";
    @JsonProperty("self")
    private String self;

    public static final String JSON_PROPERTY_FIRST = "first";
    @JsonProperty("first")
    private String first;

    public static final String JSON_PROPERTY_LAST = "last";
    @JsonProperty("last")
    private String last;

    public static final String JSON_PROPERTY_NEXT = "next";
    @JsonProperty("next")
    private String next;

    public static final String JSON_PROPERTY_PREVIOUS = "previous";
    @JsonProperty("previous")
    private String previous;

}
