/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import lombok.Data;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
* RawRequest
*/
    @JsonPropertyOrder({
        RawRequest.JSON_PROPERTY_METHOD,
        RawRequest.JSON_PROPERTY_URL,
        RawRequest.JSON_PROPERTY_REQUEST_INSTANT,
        RawRequest.JSON_PROPERTY_HEADERS,
        RawRequest.JSON_PROPERTY_BODY,
        RawRequest.JSON_PROPERTY_BODY_PARAMETERS,
        RawRequest.JSON_PROPERTY_START_TIME,
        RawRequest.JSON_PROPERTY_STARTED_AT
    })
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-15T13:40:46.583Z[Etc/UTC]")
@lombok.Builder(toBuilder=true) 
@lombok.Data
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class RawRequest {
    public static final String JSON_PROPERTY_METHOD = "method";
    @JsonProperty("method")
    private String method;

    public static final String JSON_PROPERTY_URL = "url";
    @JsonProperty("url")
    private String url;

    public static final String JSON_PROPERTY_REQUEST_INSTANT = "requestInstant";
    @JsonProperty("requestInstant")
    private OffsetDateTime requestInstant;

    public static final String JSON_PROPERTY_HEADERS = "headers";
    @JsonProperty("headers")
    @lombok.Singular("headers") private Map<String, String> headers;

    public static final String JSON_PROPERTY_BODY = "body";
    @JsonProperty("body")
    private Object body;

    public static final String JSON_PROPERTY_BODY_PARAMETERS = "bodyParameters";
    @JsonProperty("bodyParameters")
    @lombok.Singular("bodyParameters") private Map<String, String> bodyParameters;

    public static final String JSON_PROPERTY_START_TIME = "startTime";
    @JsonProperty("startTime")
    private OffsetDateTime startTime;

    public static final String JSON_PROPERTY_STARTED_AT = "startedAt";
    @JsonProperty("startedAt")
    private OffsetDateTime startedAt;

}
