/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.13.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import lombok.Data;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets VirtualAccountClientBusinessType
 */
public enum VirtualAccountClientBusinessType {
  
  SOLE_TRADER("SOLE_TRADER"),
  
  LIMITED_LIABILITY("LIMITED_LIABILITY"),
  
  CHARITY("CHARITY"),
  
  PUBLIC_LIMITED_COMPANY("PUBLIC_LIMITED_COMPANY"),
  
  ORDINARY_PARTNERSHIP("ORDINARY_PARTNERSHIP"),
  
  LIMITED_PARTNERSHIP("LIMITED_PARTNERSHIP");

  private String value;

  VirtualAccountClientBusinessType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static VirtualAccountClientBusinessType fromValue(String value) {
    for (VirtualAccountClientBusinessType b : VirtualAccountClientBusinessType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

