/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.api;

import yapily.sdk.*;
import yapily.sdk.auth.*;
import yapily.sdk.models.ApiListResponseOfFeatureDetails;
import yapily.sdk.models.ApiListResponseOfInstitution;
import yapily.sdk.models.ApiResponseError;
import yapily.sdk.models.Institution;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InstitutionsApi
 */
public class InstitutionsApiTest {

    private final InstitutionsApi api = new InstitutionsApi();

    /**
     * Get Features
     *
     * Used to retrieve all features available from Yapily. Each &#x60;Institution&#x60; supports a one, many or all of these features and can be seen in the features field of the &#x60;Institution&#x60; object.&lt;br&gt;&lt;br&gt;Note: Every &#x60;Institution&#x60; does not necessarily support every feature. To see which features are available for a particular Institution, use either the [Get Institutions](https://docs.yapily.com/api/reference/#operation/getInstitutions) or [Get Institution](https://docs.yapily.com/api/reference/#operation/getInstitution) endpoint and check the features array within the &#x60;Institution&#x60; payload.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFeatureDetailsTest() throws ApiException {
        //ApiListResponseOfFeatureDetails response = api.getFeatureDetails();
        // TODO: test validations
    }

    /**
     * Get Institution
     *
     * Used to retrieves details of a specific &#x60;Institution&#x60; within an application
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInstitutionTest() throws ApiException {
        //String institutionId = null;
        //Institution response = api.getInstitution(institutionId);
        // TODO: test validations
    }

    /**
     * Get Institutions
     *
     * Used to retrieve all &#x60;Institutions&#x60; within an application
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInstitutionsTest() throws ApiException {
        //ApiListResponseOfInstitution response = api.getInstitutions();
        // TODO: test validations
    }

}
