/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.13.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import yapily.sdk.models.AccountInfo;
import yapily.sdk.models.FeatureEnum;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AccountRequest
 */
public class AccountRequestTest {
    private final AccountRequest model = new AccountRequest();

    /**
     * Model tests for AccountRequest
     */
    @Test
    public void testAccountRequest() {
        // TODO: test AccountRequest
    }

    /**
     * Test the property 'transactionFrom'
     */
    @Test
    public void transactionFromTest() {
        // TODO: test transactionFrom
    }

    /**
     * Test the property 'transactionTo'
     */
    @Test
    public void transactionToTest() {
        // TODO: test transactionTo
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    public void expiresAtTest() {
        // TODO: test expiresAt
    }

    /**
     * Test the property 'accountIdentifiers'
     */
    @Test
    public void accountIdentifiersTest() {
        // TODO: test accountIdentifiers
    }

    /**
     * Test the property 'accountIdentifiersForTransaction'
     */
    @Test
    public void accountIdentifiersForTransactionTest() {
        // TODO: test accountIdentifiersForTransaction
    }

    /**
     * Test the property 'accountIdentifiersForBalance'
     */
    @Test
    public void accountIdentifiersForBalanceTest() {
        // TODO: test accountIdentifiersForBalance
    }

    /**
     * Test the property 'featureScope'
     */
    @Test
    public void featureScopeTest() {
        // TODO: test featureScope
    }

}
