/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.5.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import yapily.sdk.models.EmbeddedAccountAuthorisationResponse;
import yapily.sdk.models.RawResponse;
import yapily.sdk.models.ResponseForwardedData;
import yapily.sdk.models.ResponseMeta;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ApiResponseOfEmbeddedAccountAuthorisationResponse
 */
public class ApiResponseOfEmbeddedAccountAuthorisationResponseTest {
    private final ApiResponseOfEmbeddedAccountAuthorisationResponse model = new ApiResponseOfEmbeddedAccountAuthorisationResponse();

    /**
     * Model tests for ApiResponseOfEmbeddedAccountAuthorisationResponse
     */
    @Test
    public void testApiResponseOfEmbeddedAccountAuthorisationResponse() {
        // TODO: test ApiResponseOfEmbeddedAccountAuthorisationResponse
    }

    /**
     * Test the property 'meta'
     */
    @Test
    public void metaTest() {
        // TODO: test meta
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'forwardedData'
     */
    @Test
    public void forwardedDataTest() {
        // TODO: test forwardedData
    }

    /**
     * Test the property 'raw'
     */
    @Test
    public void rawTest() {
        // TODO: test raw
    }

    /**
     * Test the property 'tracingId'
     */
    @Test
    public void tracingIdTest() {
        // TODO: test tracingId
    }

}
