/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.13.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import yapily.sdk.models.EnrichedBalances;
import yapily.sdk.models.ProfileConsent;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BalancePredictionProfile
 */
public class BalancePredictionProfileTest {
    private final BalancePredictionProfile model = new BalancePredictionProfile();

    /**
     * Model tests for BalancePredictionProfile
     */
    @Test
    public void testBalancePredictionProfile() {
        // TODO: test BalancePredictionProfile
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'profileConsents'
     */
    @Test
    public void profileConsentsTest() {
        // TODO: test profileConsents
    }

    /**
     * Test the property 'enrichedBalances'
     */
    @Test
    public void enrichedBalancesTest() {
        // TODO: test enrichedBalances
    }

}
