/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.5.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.UUID;
import yapily.sdk.models.DeleteStatusEnum;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConsentDeleteResponse
 */
public class ConsentDeleteResponseTest {
    private final ConsentDeleteResponse model = new ConsentDeleteResponse();

    /**
     * Model tests for ConsentDeleteResponse
     */
    @Test
    public void testConsentDeleteResponse() {
        // TODO: test ConsentDeleteResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'deleteStatus'
     */
    @Test
    public void deleteStatusTest() {
        // TODO: test deleteStatus
    }

    /**
     * Test the property 'institutionId'
     */
    @Test
    public void institutionIdTest() {
        // TODO: test institutionId
    }

    /**
     * Test the property 'institutionConsentId'
     */
    @Test
    public void institutionConsentIdTest() {
        // TODO: test institutionConsentId
    }

    /**
     * Test the property 'creationDate'
     */
    @Test
    public void creationDateTest() {
        // TODO: test creationDate
    }

}
