/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import yapily.sdk.models.Amount;
import yapily.sdk.models.DirectDebitPayee;
import yapily.sdk.models.PaymentStatusDetails;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DirectDebitResponse
 */
public class DirectDebitResponseTest {
    private final DirectDebitResponse model = new DirectDebitResponse();

    /**
     * Model tests for DirectDebitResponse
     */
    @Test
    public void testDirectDebitResponse() {
        // TODO: test DirectDebitResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'statusDetails'
     */
    @Test
    public void statusDetailsTest() {
        // TODO: test statusDetails
    }

    /**
     * Test the property 'payeeDetails'
     */
    @Test
    public void payeeDetailsTest() {
        // TODO: test payeeDetails
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'previousPaymentAmount'
     */
    @Test
    public void previousPaymentAmountTest() {
        // TODO: test previousPaymentAmount
    }

    /**
     * Test the property 'previousPaymentDateTime'
     */
    @Test
    public void previousPaymentDateTimeTest() {
        // TODO: test previousPaymentDateTime
    }

}
