/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.13.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import yapily.sdk.models.Categorisation;
import yapily.sdk.models.EnrichmentMerchant;
import yapily.sdk.models.TransactionHash;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Enrichment
 */
public class EnrichmentTest {
    private final Enrichment model = new Enrichment();

    /**
     * Model tests for Enrichment
     */
    @Test
    public void testEnrichment() {
        // TODO: test Enrichment
    }

    /**
     * Test the property 'categorisation'
     */
    @Test
    public void categorisationTest() {
        // TODO: test categorisation
    }

    /**
     * Test the property 'transactionHash'
     */
    @Test
    public void transactionHashTest() {
        // TODO: test transactionHash
    }

    /**
     * Test the property 'cleansedDescription'
     */
    @Test
    public void cleansedDescriptionTest() {
        // TODO: test cleansedDescription
    }

    /**
     * Test the property 'merchant'
     */
    @Test
    public void merchantTest() {
        // TODO: test merchant
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'paymentProcessor'
     */
    @Test
    public void paymentProcessorTest() {
        // TODO: test paymentProcessor
    }

    /**
     * Test the property 'correctedDate'
     */
    @Test
    public void correctedDateTest() {
        // TODO: test correctedDate
    }

}
