/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.13.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.LocalDate;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EnrichedPredictedBalance
 */
public class EnrichedPredictedBalanceTest {
    private final EnrichedPredictedBalance model = new EnrichedPredictedBalance();

    /**
     * Model tests for EnrichedPredictedBalance
     */
    @Test
    public void testEnrichedPredictedBalance() {
        // TODO: test EnrichedPredictedBalance
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'medianBalance'
     */
    @Test
    public void medianBalanceTest() {
        // TODO: test medianBalance
    }

    /**
     * Test the property '_90percentileBalance'
     */
    @Test
    public void _90percentileBalanceTest() {
        // TODO: test _90percentileBalance
    }

    /**
     * Test the property '_10percentileBalance'
     */
    @Test
    public void _10percentileBalanceTest() {
        // TODO: test _10percentileBalance
    }

}
