/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.6.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import yapily.sdk.models.RateTypeEnum;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ExchangeRateInformationResponse
 */
public class ExchangeRateInformationResponseTest {
    private final ExchangeRateInformationResponse model = new ExchangeRateInformationResponse();

    /**
     * Model tests for ExchangeRateInformationResponse
     */
    @Test
    public void testExchangeRateInformationResponse() {
        // TODO: test ExchangeRateInformationResponse
    }

    /**
     * Test the property 'unitCurrency'
     */
    @Test
    public void unitCurrencyTest() {
        // TODO: test unitCurrency
    }

    /**
     * Test the property 'rate'
     */
    @Test
    public void rateTest() {
        // TODO: test rate
    }

    /**
     * Test the property 'rateType'
     */
    @Test
    public void rateTypeTest() {
        // TODO: test rateType
    }

    /**
     * Test the property 'foreignExchangeContractReference'
     */
    @Test
    public void foreignExchangeContractReferenceTest() {
        // TODO: test foreignExchangeContractReference
    }

    /**
     * Test the property 'exchangeRateExpiryDate'
     */
    @Test
    public void exchangeRateExpiryDateTest() {
        // TODO: test exchangeRateExpiryDate
    }

}
