/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import yapily.sdk.models.ChargeBearerType;
import yapily.sdk.models.ExchangeRateInformation;
import yapily.sdk.models.PriorityCodeEnum;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InternationalPaymentRequest
 */
public class InternationalPaymentRequestTest {
    private final InternationalPaymentRequest model = new InternationalPaymentRequest();

    /**
     * Model tests for InternationalPaymentRequest
     */
    @Test
    public void testInternationalPaymentRequest() {
        // TODO: test InternationalPaymentRequest
    }

    /**
     * Test the property 'currencyOfTransfer'
     */
    @Test
    public void currencyOfTransferTest() {
        // TODO: test currencyOfTransfer
    }

    /**
     * Test the property 'exchangeRateInformation'
     */
    @Test
    public void exchangeRateInformationTest() {
        // TODO: test exchangeRateInformation
    }

    /**
     * Test the property 'purpose'
     */
    @Test
    public void purposeTest() {
        // TODO: test purpose
    }

    /**
     * Test the property 'priority'
     */
    @Test
    public void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'chargeBearer'
     */
    @Test
    public void chargeBearerTest() {
        // TODO: test chargeBearer
    }

}
