/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.6.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import yapily.sdk.models.MultiAuthorisation;
import yapily.sdk.models.PaymentIsoStatus;
import yapily.sdk.models.PaymentStatus;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PaymentStatusDetails
 */
public class PaymentStatusDetailsTest {
    private final PaymentStatusDetails model = new PaymentStatusDetails();

    /**
     * Model tests for PaymentStatusDetails
     */
    @Test
    public void testPaymentStatusDetails() {
        // TODO: test PaymentStatusDetails
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'statusReason'
     */
    @Test
    public void statusReasonTest() {
        // TODO: test statusReason
    }

    /**
     * Test the property 'statusReasonDescription'
     */
    @Test
    public void statusReasonDescriptionTest() {
        // TODO: test statusReasonDescription
    }

    /**
     * Test the property 'statusUpdateDate'
     */
    @Test
    public void statusUpdateDateTest() {
        // TODO: test statusUpdateDate
    }

    /**
     * Test the property 'multiAuthorisationStatus'
     */
    @Test
    public void multiAuthorisationStatusTest() {
        // TODO: test multiAuthorisationStatus
    }

    /**
     * Test the property 'isoStatus'
     */
    @Test
    public void isoStatusTest() {
        // TODO: test isoStatus
    }

}
