/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.5.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import yapily.sdk.models.Amount;
import yapily.sdk.models.PaymentContextType;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SubmissionRequest
 */
public class SubmissionRequestTest {
    private final SubmissionRequest model = new SubmissionRequest();

    /**
     * Model tests for SubmissionRequest
     */
    @Test
    public void testSubmissionRequest() {
        // TODO: test SubmissionRequest
    }

    /**
     * Test the property 'paymentIdempotencyId'
     */
    @Test
    public void paymentIdempotencyIdTest() {
        // TODO: test paymentIdempotencyId
    }

    /**
     * Test the property 'psuAuthenticationMethod'
     */
    @Test
    public void psuAuthenticationMethodTest() {
        // TODO: test psuAuthenticationMethod
    }

    /**
     * Test the property 'contextType'
     */
    @Test
    public void contextTypeTest() {
        // TODO: test contextType
    }

    /**
     * Test the property 'paymentAmount'
     */
    @Test
    public void paymentAmountTest() {
        // TODO: test paymentAmount
    }

}
