/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.6.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import yapily.sdk.models.InitiationDetails;
import yapily.sdk.models.Payer;
import yapily.sdk.models.PaymentStatus;
import yapily.sdk.models.PaymentStatusDetails;
import yapily.sdk.models.RefundAccount;
import yapily.sdk.models.SubmissionDetails;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SubmissionResponse
 */
public class SubmissionResponseTest {
    private final SubmissionResponse model = new SubmissionResponse();

    /**
     * Model tests for SubmissionResponse
     */
    @Test
    public void testSubmissionResponse() {
        // TODO: test SubmissionResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'paymentIdempotencyId'
     */
    @Test
    public void paymentIdempotencyIdTest() {
        // TODO: test paymentIdempotencyId
    }

    /**
     * Test the property 'institutionConsentId'
     */
    @Test
    public void institutionConsentIdTest() {
        // TODO: test institutionConsentId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'statusDetails'
     */
    @Test
    public void statusDetailsTest() {
        // TODO: test statusDetails
    }

    /**
     * Test the property 'initiationDetails'
     */
    @Test
    public void initiationDetailsTest() {
        // TODO: test initiationDetails
    }

    /**
     * Test the property 'submissionDetails'
     */
    @Test
    public void submissionDetailsTest() {
        // TODO: test submissionDetails
    }

    /**
     * Test the property 'payer'
     */
    @Test
    public void payerTest() {
        // TODO: test payer
    }

    /**
     * Test the property 'refundAccount'
     */
    @Test
    public void refundAccountTest() {
        // TODO: test refundAccount
    }

    /**
     * Test the property 'expectedExecutionTime'
     */
    @Test
    public void expectedExecutionTimeTest() {
        // TODO: test expectedExecutionTime
    }

    /**
     * Test the property 'expectedSettlementTime'
     */
    @Test
    public void expectedSettlementTimeTest() {
        // TODO: test expectedSettlementTime
    }

}
