/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.6.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import yapily.sdk.models.Amount;
import yapily.sdk.models.SweepingPeriodicLimits;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SweepingControlParameters
 */
public class SweepingControlParametersTest {
    private final SweepingControlParameters model = new SweepingControlParameters();

    /**
     * Model tests for SweepingControlParameters
     */
    @Test
    public void testSweepingControlParameters() {
        // TODO: test SweepingControlParameters
    }

    /**
     * Test the property 'psuAuthenticationMethods'
     */
    @Test
    public void psuAuthenticationMethodsTest() {
        // TODO: test psuAuthenticationMethods
    }

    /**
     * Test the property 'periodicLimits'
     */
    @Test
    public void periodicLimitsTest() {
        // TODO: test periodicLimits
    }

    /**
     * Test the property 'maxAmountPerPayment'
     */
    @Test
    public void maxAmountPerPaymentTest() {
        // TODO: test maxAmountPerPayment
    }

    /**
     * Test the property 'validFrom'
     */
    @Test
    public void validFromTest() {
        // TODO: test validFrom
    }

    /**
     * Test the property 'validTo'
     */
    @Test
    public void validToTest() {
        // TODO: test validTo
    }

}
