/*
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.5.0
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package yapily.sdk.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import yapily.sdk.models.AccountIdentification;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VirtualAccountBankAccount
 */
public class VirtualAccountBankAccountTest {
    private final VirtualAccountBankAccount model = new VirtualAccountBankAccount();

    /**
     * Model tests for VirtualAccountBankAccount
     */
    @Test
    public void testVirtualAccountBankAccount() {
        // TODO: test VirtualAccountBankAccount
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'bankName'
     */
    @Test
    public void bankNameTest() {
        // TODO: test bankName
    }

    /**
     * Test the property 'bankAddress'
     */
    @Test
    public void bankAddressTest() {
        // TODO: test bankAddress
    }

    /**
     * Test the property 'bankCountry'
     */
    @Test
    public void bankCountryTest() {
        // TODO: test bankCountry
    }

    /**
     * Test the property 'accountIdentifications'
     */
    @Test
    public void accountIdentificationsTest() {
        // TODO: test accountIdentifications
    }

    /**
     * Test the property 'payInReference'
     */
    @Test
    public void payInReferenceTest() {
        // TODO: test payInReference
    }

}
