/*
 * Yapily API
 * To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)
 *
 * OpenAPI spec version: 0.0.159
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package yapily.sdk;

import lombok.Data;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Consent
 */
@Data
public class Consent {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("userUuid")
  private String userUuid = null;

  @JsonProperty("applicationUserId")
  private String applicationUserId = null;

  @JsonProperty("referenceId")
  private String referenceId = null;

  @JsonProperty("institutionId")
  private String institutionId = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    AWAITING_AUTHORIZATION("AWAITING_AUTHORIZATION"),
    
    AWAITING_FURTHER_AUTHORIZATION("AWAITING_FURTHER_AUTHORIZATION"),
    
    AWAITING_RE_AUTHORIZATION("AWAITING_RE_AUTHORIZATION"),
    
    AUTHORIZED("AUTHORIZED"),
    
    CONSUMED("CONSUMED"),
    
    REJECTED("REJECTED"),
    
    REVOKED("REVOKED"),
    
    FAILED("FAILED"),
    
    EXPIRED("EXPIRED"),
    
    UNKNOWN("UNKNOWN"),
    
    INVALID("INVALID");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("createdAt")
  private OffsetDateTime createdAt = null;

  @JsonProperty("transactionFrom")
  private OffsetDateTime transactionFrom = null;

  @JsonProperty("transactionTo")
  private OffsetDateTime transactionTo = null;

  @JsonProperty("expiresAt")
  private OffsetDateTime expiresAt = null;

  @JsonProperty("timeToExpireInMillis")
  private Long timeToExpireInMillis = null;

  @JsonProperty("timeToExpire")
  private String timeToExpire = null;

  /**
   * Gets or Sets featureScope
   */
  public enum FeatureScopeEnum {
    INITIATE_ACCOUNT_REQUEST("INITIATE_ACCOUNT_REQUEST"),
    
    ACCOUNT_REQUEST_DETAILS("ACCOUNT_REQUEST_DETAILS"),
    
    ACCOUNTS("ACCOUNTS"),
    
    ACCOUNT("ACCOUNT"),
    
    ACCOUNT_TRANSACTIONS("ACCOUNT_TRANSACTIONS"),
    
    ACCOUNT_STATEMENTS("ACCOUNT_STATEMENTS"),
    
    ACCOUNT_STATEMENT("ACCOUNT_STATEMENT"),
    
    ACCOUNT_STATEMENT_FILE("ACCOUNT_STATEMENT_FILE"),
    
    ACCOUNT_SCHEDULED_PAYMENTS("ACCOUNT_SCHEDULED_PAYMENTS"),
    
    ACCOUNT_DIRECT_DEBITS("ACCOUNT_DIRECT_DEBITS"),
    
    ACCOUNT_PERIODIC_PAYMENTS("ACCOUNT_PERIODIC_PAYMENTS"),
    
    ACCOUNT_TRANSACTIONS_WITH_MERCHANT("ACCOUNT_TRANSACTIONS_WITH_MERCHANT"),
    
    IDENTITY("IDENTITY"),
    
    INITIATE_SINGLE_PAYMENT_SORTCODE("INITIATE_SINGLE_PAYMENT_SORTCODE"),
    
    EXISTING_PAYMENT_INITIATION_DETAILS("EXISTING_PAYMENT_INITIATION_DETAILS"),
    
    CREATE_SINGLE_PAYMENT_SORTCODE("CREATE_SINGLE_PAYMENT_SORTCODE"),
    
    EXISTING_PAYMENTS_DETAILS("EXISTING_PAYMENTS_DETAILS"),
    
    INITIATE_PAYMENT("INITIATE_PAYMENT"),
    
    CREATE_PAYMENT("CREATE_PAYMENT"),
    
    INITIATE_DOMESTIC_VARIABLE_RECURRING_PAYMENT("INITIATE_DOMESTIC_VARIABLE_RECURRING_PAYMENT"),
    
    CREATE_DOMESTIC_VARIABLE_RECURRING_PAYMENT("CREATE_DOMESTIC_VARIABLE_RECURRING_PAYMENT"),
    
    INITIATE_DOMESTIC_SCHEDULED_PAYMENT("INITIATE_DOMESTIC_SCHEDULED_PAYMENT"),
    
    CREATE_DOMESTIC_SCHEDULED_PAYMENT("CREATE_DOMESTIC_SCHEDULED_PAYMENT"),
    
    INITIATE_DOMESTIC_PERIODIC_PAYMENT("INITIATE_DOMESTIC_PERIODIC_PAYMENT"),
    
    CREATE_DOMESTIC_PERIODIC_PAYMENT("CREATE_DOMESTIC_PERIODIC_PAYMENT"),
    
    PERIODIC_PAYMENT_FREQUENCY_EXTENDED("PERIODIC_PAYMENT_FREQUENCY_EXTENDED"),
    
    INITIATE_INTERNATIONAL_VARIABLE_RECURRING_PAYMENT("INITIATE_INTERNATIONAL_VARIABLE_RECURRING_PAYMENT"),
    
    CREATE_INTERNATIONAL_VARIABLE_RECURRING_PAYMENT("CREATE_INTERNATIONAL_VARIABLE_RECURRING_PAYMENT"),
    
    INITIATE_INTERNATIONAL_SCHEDULED_PAYMENT("INITIATE_INTERNATIONAL_SCHEDULED_PAYMENT"),
    
    CREATE_INTERNATIONAL_SCHEDULED_PAYMENT("CREATE_INTERNATIONAL_SCHEDULED_PAYMENT"),
    
    INITIATE_INTERNATIONAL_PERIODIC_PAYMENT_ORDER("INITIATE_INTERNATIONAL_PERIODIC_PAYMENT_ORDER"),
    
    CREATE_INTERNATIONAL_PERIODIC_PAYMENT_ORDER("CREATE_INTERNATIONAL_PERIODIC_PAYMENT_ORDER"),
    
    INITIATE_INTERNATIONAL_PAYMENT("INITIATE_INTERNATIONAL_PAYMENT"),
    
    CREATE_INTERNATIONAL_PAYMENT("CREATE_INTERNATIONAL_PAYMENT"),
    
    TRANSFER("TRANSFER"),
    
    OPEN_DATA_PERSONAL_CURRENT_ACCOUNTS("OPEN_DATA_PERSONAL_CURRENT_ACCOUNTS"),
    
    OPEN_DATA_ATMS("OPEN_DATA_ATMS");

    private String value;

    FeatureScopeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FeatureScopeEnum fromValue(String text) {
      for (FeatureScopeEnum b : FeatureScopeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("featureScope")
  private List<FeatureScopeEnum> featureScope = null;

  @JsonProperty("startsAt")
  private OffsetDateTime startsAt = null;

  @JsonProperty("totalMaxAmount")
  private BigDecimal totalMaxAmount = null;

  @JsonProperty("maxAmountPerRequest")
  private BigDecimal maxAmountPerRequest = null;

  @JsonProperty("allowOverdraft")
  private Boolean allowOverdraft = null;

  @JsonProperty("consentToken")
  private String consentToken = null;

}

