/*
 * Yapily API
 * To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)
 *
 * OpenAPI spec version: 0.0.332
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package yapily.sdk;

import lombok.Data;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;

/**
 * ConsentDeleteResponse
 */
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class ConsentDeleteResponse {
  @JsonProperty("id")
  private String id = null;

  /**
   * Gets or Sets deleteStatus
   */
  public enum DeleteStatusEnum {
    SUCCESS("SUCCESS"),
    
    FAILED("FAILED");

    private String value;

    DeleteStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DeleteStatusEnum fromValue(String text) {
      for (DeleteStatusEnum b : DeleteStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("deleteStatus")
  private DeleteStatusEnum deleteStatus = null;

  @JsonProperty("institutionId")
  private String institutionId = null;

  @JsonProperty("institutionConsentId")
  private String institutionConsentId = null;

  @JsonProperty("creationDate")
  private OffsetDateTime creationDate = null;

}

